### ISSUE TITLE
一点建议和反馈

### ISSUE THREAD

**Issue by ajavaer** [ethtweet/ethtweet#46]
1.希望点击评论，除了可以发表评论，下面也会展示当前评论列表，可以分页那种，类似微博。
2.目前的搜索功能好像无效果。
3.希望支持中文切换。
4.右上角的Setting主题好像只有Dark Mode可以用。
5.移动端的Help点击无反应。
6.保存用户信息接口好像比较卡，20多秒。

**Comment by chenjia404** [comment]
1.评论功能后续增加。
2.搜索功能后续增加
3.多语言支持也可以增加
4.可以修改颜色
5.移动端后续优化
6.这个接口后续优化
